apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-deployment
  template:
    metadata:
      labels:
        app: next-deployment
    spec:
      containers:
      - name: next-deployment
        image: 192.168.49.3:5000/next-app
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"